# Generated by Django 2.0 on 2018-07-11 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='thunbnail',
            new_name='thumbnail',
        ),
    ]
