# Generated by Django 2.0 on 2018-08-02 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_courseorder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseorder',
            name='istype',
            field=models.SmallIntegerField(default=0),
        ),
    ]
