# Generated by Django 2.0 on 2018-08-02 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Payinfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField()),
                ('path', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('profile', models.CharField(max_length=100)),
            ],
        ),
    ]
