# Generated by Django 2.0 on 2018-08-02 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payinfo', '0003_payinfoorder_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payinfoorder',
            name='status',
            field=models.SmallIntegerField(default=1, null=True),
        ),
    ]
