# Generated by Django 2.0 on 2018-08-02 07:58

from django.db import migrations
import shortuuidfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('payinfo', '0004_auto_20180802_1526'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payinfoorder',
            name='id',
        ),
        migrations.AddField(
            model_name='payinfoorder',
            name='uid',
            field=shortuuidfield.fields.ShortUUIDField(blank=True, editable=False, max_length=22, primary_key=True, serialize=False),
        ),
    ]
