# Generated by Django 2.0 on 2018-08-02 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payinfo', '0005_auto_20180802_1558'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payinfoorder',
            name='istype',
            field=models.SmallIntegerField(default=0),
        ),
    ]
