# Generated by Django 2.0 on 2018-07-11 03:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NewCategory',
        ),
    ]
